### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by GreenKudu** [Jeoxs/khanos#16]
Hello,

After logging in, I get a completely blank screen after login in all 3 tabs (Home, Overdue Tasks, Activities). No error messages are displayed. The home tab is completely gray, Overdue tasks shows a 'loading bars' image, similarly to Activities. I can successfully add new projects (normal and/or personal projects) using the '+' button, and they are shown through the website, but not within the app.

I have tried this with both a normal user, a manager user as well as with the admin user, all with the same results. Tried this in both the latest version and 1.1.4. I can see in the Kanboard server logs that it is successfully hitting the API page (jsonrpc.php). When enabling debug mode in Kanboard I can see queries being executed, although I haven't looked much further.

How can I further debug what is going on?

**Comment by Jeoxs** [comment]
Hello @GreenKudu and thank you for the report. Can you tell me which version of kanboard are you using on your endpoint?

The projects page uses the API method "getmyProjects" which retrieves the projects created by the user and the ones where the user is part of. 

I'll try to replicate this and see what might be happening.

**Comment by GreenKudu** [comment]
I'm on kanboard 1.2.20

**Comment by Jeoxs** [comment]
Hey! sorry for keeping you waiting so long. Could you install the newer version of Khanos and see if you get the same results?

**Comment by GreenKudu** [comment]
Sorry, I cannot test this anymore since I abandoned Kanboard altogether after being unable to find a usable mobile app.

**Comment by alexodus** [comment]
I have the same problem. I'm forked this repo (and made some needed change for compilation).
I'm using [Kanboard 1.2.22](https://github.com/kanboard/kanboard/releases/tag/v1.2.22)

<img width="792" alt="image" src="https://user-images.githubusercontent.com/2721510/159130821-f9a63c9d-d6c5-4fd2-ac62-8184770b794c.png">

**Comment by alexodus** [comment]
issue: all field type in dart model are **String**, but in the json they are often **int**

**Comment by alexodus** [comment]
see to my fork for some changes: https://github.com/alexodus/khanos

**Comment by Jeoxs** [comment]
Hey @alexodus ! Thank you for your support. The solution you implemented is ideal!

**Comment by vmario89** [comment]
Hi. I have the exact same issue that still nothing is shown in app, but i can add new project which can be seen in browser. We are running Kanboard v1.2.22 and Khanos 1.1.6 (latest version). I already tried to use different users but no difference. Any idea what could still be the cause?

**Comment by vmario89** [comment]
```adb logcat``` says:
```
05-08 22:45:34.165 20235 20270 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '_Smi' is not a subtype of type 'String'
05-08 22:45:34.165 20235 20270 E flutter : #0      new ProjectModel.fromJson (package:khanos/src/models/project_model.dart:60)
05-08 22:45:34.165 20235 20270 E flutter : #1      ProjectProvider.getProjects.<anonymous closure> (package:khanos/src/providers/project_provider.dart:47)
05-08 22:45:34.165 20235 20270 E flutter : #2      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
05-08 22:45:34.165 20235 20270 E flutter : #3      ProjectProvider.getProjects (package:khanos/src/providers/project_provider.dart:46)
05-08 22:45:34.165 20235 20270 E flutter : <asynchronous suspension>
05-08 22:45:34.165 20235 20270 E flutter : #4      Future.wait.<anonymous closure> (dart:async/future.dart)
05-08 22:45:34.165 20235 20270 E flutter : <asynchronous suspension>
05-08 22:45:34.165 20235 20270 E flutter : 
```

**Comment by ianme** [comment]
Exactly the same problem, with Kanboard 1.2.22 and Khanos 1.1.6.
~~Even projects created through Khanos don't appear anywhere.~~

Edit: projects created through Khanos do appear on Kanboard, but still not in the app.

**Comment by phenexos** [comment]
Hello,

If I understand correctly, there is a patch for this issue. Would it be possible to build an APK with that patch ?

**Comment by tripleFA** [comment]
Hi,
I build an APK from @alexodus's  fork : 
https://github.com/tripleFA/khanos/releases/tag/1.1.6_1

**Comment by vmario89** [comment]
hey. cool this works now, except the Activites tab. This is still loading infinetely
![Screenshot_20220804_183337_com gojaponte khanos](https://user-images.githubusercontent.com/5631071/182903794-c0b74479-0643-49f5-8c7b-6e5832e0c297.jpg)

**Comment by vmario89** [comment]
and the comments for a task are not loaded too in your version. but its still really cool you invested time to fix a lot of non-working stuff to make it work again!

**Comment by tripleFA** [comment]
I'll see what I can do but it was my first time compiling an Android app. I didn't even install AS and I don't know how to develop in Dart.

**Comment by vmario89** [comment]
me too. I am just the dumb user which can install and test out different things. But as i really like to work with Kanboard, Khanos will be a good tool to make it smarter when being off from a regular computer. 

the unshown activities might be the following error. i did not get a more detailed exception yet. ```adb logcat --pid=`adb shell pidof -s com.gojaponte.khanos` ```

`08-07 11:35:57.082 20327 20327 E Parcel  : Reading a NULL string not supported here.`


i opened a new issue to show the error for task comments: https://github.com/Jeoxs/khanos/issues/32

**Comment by tripleFA** [comment]
@vmario89  : I fixed activities and comments page : 
https://github.com/tripleFA/khanos/releases/tag/1.1.6_2

**Comment by vmario89** [comment]
@tripleFA great. you did it! this works perfectly! Thanks a lot for your share

**Comment by ianme** [comment]
@tripleFA thank you for these corrections! everything works fine with 1.1.6_2 except... swimlanes! Have you any idea about that?

Will these updates go back into the main stream and proposed to everyone via Aurora/Play Store?

Kind regards,
Iannis

**Comment by vmario89** [comment]
as long as @Jeoxs does not merge those changes it might stay a fork

**Comment by tripleFA** [comment]
I never seen the app working.  Swimlanes where shown on project page?
As I understand swimlanes infos are requested from the server only when a task is opened and displayed between assigned user and estimated time.

As @vmario89  said it will stay a fork until @Jeoxs merge those changes.

**Comment by ghost** [comment]
thank you so much @tripleFA, got it working thanks to your fork <3
